### ISSUE TITLE
Conflicts with BetterShutdown tweak

### ISSUE THREAD

**Issue by frakman1** [peterprd/PowerGuard#1]
iOS 10.3 on iPhoneSE

I use a tweak called [BetterShutdown](http://cydia.saurik.com/package/com.dbdexter.bettershutdown/) that gives options to the following when holding the power button: 

- Power Off
- Reboot
- Respring
- SafeMode 

When I select Power Off, it crashes and goes to SafeMode. Is there any way you could make it so PowerGuard works nicely with BetterShutdown?

Thank you.

**Comment by s8ngyu** [comment]
This should fix by BetterShutdown developer.
